[pastebin-api-client]
    type = 'pastebin-api-client'
    api_dev_key = ''
    api_user_key = ''
    users_list = [
                 ]
    key = ""
    sig = ""
    cse_cx = ""
    query = ""
    cse_tok = ""